baseURL = "/"
languageCode = "en-us"
title = "Education"

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/zerostaticthemes/hugo-serif-theme"

[params]
  # Optional: set a default description used in meta tags
  description = "Resources and guidance on education, colleges, and programs."

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
