baseURL = "https://kylejones200.github.io/education/"
languageCode = "en-us"
title = "Education"

[pagination]
  pagerSize = 10

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "title"
    weight = 40
  [[related.indices]]
    name = "date"
    weight = 10

[outputs]
  home = ["HTML", "JSON"]

[params]
  # Optional: set a default description used in meta tags
  description = "Resources and guidance on education, colleges, and programs."

  # Favicon paths (used by some themes to render <link rel="icon"> automatically)
  favicon = "favicon.svg"
  favicon_ico = "favicon.ico"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  # ---- PaperMod options ----
  # Theme behavior
  defaultTheme = "auto"          # "light", "dark", or "auto"
  disableThemeToggle = false

  # Post/article UX
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true

  # Table of Contents
  ShowToc = true
  TocOpen = false                 # set true to have TOC expanded by default
  UseHugoToc = true               # use Hugo's built-in TOC rendering

  # Listing/section options
  ShowRssButtonInSectionTermList = true

  # Cover/featured images
  [params.cover]
    hidden = false                # show cover on list and single
    hiddenInList = false
    hiddenInSingle = false
    linkFullImages = true

  # Home page intro (shown on the homepage above the list)
  [params.homeInfoParams]
    Title = "Education Resources"
    Content = "Guides on schools, scholarships, communications, and more."

  # Contact form configuration
  [params.contact]
    # EITHER set a Formspree endpoint to receive emails via a hosted form service:
    # formspree_endpoint = "https://formspree.io/f/your_form_id"
    # OR set a direct email to show a mailto button instead of a form:
    email = "kyle@kyletjones.com"
    # After submit, redirect to this page (we create /thanks/ below):
    redirect = "/thanks/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

# Add About to the main menu (Serif theme supports menu.main)
[menu]
  [[menu.main]]
    name = "Schools"
    url = "/schools/"
    weight = 10

  [[menu.main]]
    name = "Scholarships"
    url = "/scholarships/"
    weight = 20

  [[menu.main]]
    name = "Communication"
    url = "/communications/"
    weight = 30

  [[menu.main]]
    name = "Advice"
    url = "/advice/"
    weight = 40

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

