name: PR Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build site (no deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        run: |
          HUGO_DEB=https://github.com/gohugoio/hugo/releases/download/v0.129.0/hugo_extended_0.129.0_linux-amd64.deb
          curl -L "$HUGO_DEB" -o hugo.deb
          sudo dpkg -i hugo.deb
          hugo version

      - name: Install Dart Sass
        run: |
          sudo snap install dart-sass
          sass --version || true

      - name: Build
        run: |
          hugo --minify --gc --cleanDestinationDir

      - name: Upload public artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  lychee:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --request-timeout 20s ./public ./content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  htmltest:
    name: HTML validation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public
      - name: Run htmltest
        uses: wjdp/htmltest-action@v0.16.1
        with:
          path: ./public

  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.jsonc
        continue-on-error: true

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          skip: .git,public,resources,node_modules
          ignore_words_list: falese,nd,teh
        continue-on-error: true
